[workspace]
resolver = "2"
members = [
    "dynamics-cli",
    "dynamics-lib-macros",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Konsta Kuosmanen <konsta@kuosmanen.dev>"]
repository = "https://github.com/norpie/dynamics-cli"
license = "MIT OR Apache-2.0"
