[profile.default]
# Number of threads to use for testing
test-threads = 4

# Show output for passing tests
success-output = "never"

# Show output for failing tests
failure-output = "immediate"

# Timeout for tests
slow-timeout = { period = "60s", terminate-after = 2 }

[profile.default.junit]
# Generate JUnit XML output
path = "target/nextest/junit.xml"

[profile.ci]
# CI-specific profile with more verbose output
test-threads = 2
success-output = "never"
failure-output = "immediate"
slow-timeout = { period = "30s", terminate-after = 1 }

[profile.ci.junit]
path = "target/nextest/ci-junit.xml"

[profile.fql]
# Profile specifically for FQL parser tests
test-threads = 1
success-output = "immediate"
failure-output = "immediate"
slow-timeout = { period = "120s", terminate-after = 3 }

[profile.fql.junit]
path = "target/nextest/fql-junit.xml"